---
- include: utilities.yml
- include: awscli.yml
- include: chrome.yml
#- include: docker.yml
- include: postman.yml
- include: skype.yml
- include: spotify.yml
- include: sublime.yml
- include: vscode.yml
- include: teamviewer.yml
- include: terraform.yml
- include: tilix.yml
#- include: virtualbox.yml
- include: zsh.yml
