---
- name: create download directory
  file:
    state: directory
    mode: u=rwx,go=rx
    dest: "{{ skype_download_dir }}"

- name: download skype
  get_url:
    url: "{{ skype_url_download }}"
    dest: "{{ skype_download_dir }}/{{ skype_filename }}"
    mode: u=rw,go=r
    
- name: Install skype
  apt:
    deb: "{{ skype_download_dir }}/{{ skype_filename }}"
