---
- name:  Teamviewer - Apt signing key.
  apt_key:
    url: https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc
    state: present

- name: Teamviewer - Install repo.
  become: yes
  apt_repository:
    repo: deb http://linux.teamviewer.com/deb stable main
    filename: teamviewer
    state: present
    update_cache: yes

- name: Teamviewer - Install.
  apt:
    name: teamviewer
    state: present
