---
- name: Tilix - Install repo.
  become: yes
  apt_repository:
    repo: ppa:webupd8team/terminix
    filename: tilix
    state: present
    update_cache: yes

- name: Tilix - Install.
  apt:
    name: tilix
    state: present

- name: Tilix - Create link.
  file:
    src: /etc/profile.d/vte-2.91.sh
    dest: /etc/profile.d/vte.sh
    state: link
