---
- name: Virtualbox - Install repo.
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ distribution }} contrib
    filename: virtualbox.list
    state: present
    update_cache: yes

- name: Virtualbox - Install.
  apt:
    name: "virtualbox-{{ virtualbox_version }}"
    state: present

- name: Virtualbox - Ensure virtualbox users are added to the vbox group.
  user:
    name: "{{ item }}"
    groups: vboxusers
    append: true
  with_items: "{{ usuario }}"
  when: usuario | length > 0