---
- name: Virtualbox - Install key 2016.
  shell: "wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -"

- name: Virtualbox - Install key.
  shell: "wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -"

- name: Virtualbox - Install repo.
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    filename: virtualbox.list
    state: present
    update_cache: yes

- name: Virtualbox - Install.
  apt:
    name: "virtualbox-{{ virtualbox_version }}"
    state: present

- name: Virtualbox - Ensure virtualbox users are added to the vbox group.
  user:
    name: "{{ item }}"
    groups: vboxusers
    append: true
  with_items: "{{ usuario }}"
  when: usuario | length > 0